/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'description' : string,
  'isActive' : boolean,
}
export interface Job {
  'id' : bigint,
  'title' : string,
  'applyLink' : string,
  'postedDate' : string,
  'vacancies' : bigint,
  'isActive' : boolean,
  'category' : Type,
  'department' : string,
  'lastDate' : string,
  'qualification' : string,
}
export type Type = { 'csc' : null } |
  { 'railway' : null } |
  { 'stateGovt' : null } |
  { 'banking' : null } |
  { 'defence' : null } |
  { 'centralGovt' : null };
export interface _SERVICE {
  'addAlert' : ActorMethod<[string, string, string, string], undefined>,
  'addJob' : ActorMethod<
    [string, string, string, Type, bigint, string, string, string, string],
    undefined
  >,
  'addSampleData' : ActorMethod<[string], undefined>,
  'deleteAlert' : ActorMethod<[string, bigint], undefined>,
  'deleteJob' : ActorMethod<[string, bigint], undefined>,
  'getAllActiveAlerts' : ActorMethod<[], Array<Alert>>,
  'getAllActiveJobs' : ActorMethod<[], Array<Job>>,
  'getJobById' : ActorMethod<[bigint], Job>,
  'getJobsByCategory' : ActorMethod<[Type], Array<Job>>,
  'updateAlert' : ActorMethod<
    [string, bigint, string, string, string, boolean],
    undefined
  >,
  'updateJob' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      Type,
      bigint,
      string,
      string,
      string,
      boolean,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];