/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Type = IDL.Variant({
  'csc' : IDL.Null,
  'railway' : IDL.Null,
  'stateGovt' : IDL.Null,
  'banking' : IDL.Null,
  'defence' : IDL.Null,
  'centralGovt' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'applyLink' : IDL.Text,
  'postedDate' : IDL.Text,
  'vacancies' : IDL.Nat,
  'isActive' : IDL.Bool,
  'category' : Type,
  'department' : IDL.Text,
  'lastDate' : IDL.Text,
  'qualification' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAlert' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Type,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'addSampleData' : IDL.Func([IDL.Text], [], []),
  'deleteAlert' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteJob' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllActiveAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getAllActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getJobById' : IDL.Func([IDL.Nat], [Job], ['query']),
  'getJobsByCategory' : IDL.Func([Type], [IDL.Vec(Job)], ['query']),
  'updateAlert' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateJob' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Type,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Type = IDL.Variant({
    'csc' : IDL.Null,
    'railway' : IDL.Null,
    'stateGovt' : IDL.Null,
    'banking' : IDL.Null,
    'defence' : IDL.Null,
    'centralGovt' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'applyLink' : IDL.Text,
    'postedDate' : IDL.Text,
    'vacancies' : IDL.Nat,
    'isActive' : IDL.Bool,
    'category' : Type,
    'department' : IDL.Text,
    'lastDate' : IDL.Text,
    'qualification' : IDL.Text,
  });
  
  return IDL.Service({
    'addAlert' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'addJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Type,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'addSampleData' : IDL.Func([IDL.Text], [], []),
    'deleteAlert' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteJob' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllActiveAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getAllActiveJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getJobById' : IDL.Func([IDL.Nat], [Job], ['query']),
    'getJobsByCategory' : IDL.Func([Type], [IDL.Vec(Job)], ['query']),
    'updateAlert' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateJob' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Type,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };