/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Job {
    id: bigint;
    title: string;
    applyLink: string;
    postedDate: string;
    vacancies: bigint;
    isActive: boolean;
    category: Type;
    department: string;
    lastDate: string;
    qualification: string;
}
export interface Alert {
    id: bigint;
    title: string;
    date: string;
    description: string;
    isActive: boolean;
}
export enum Type {
    csc = "csc",
    railway = "railway",
    stateGovt = "stateGovt",
    banking = "banking",
    defence = "defence",
    centralGovt = "centralGovt"
}
export interface backendInterface {
    addAlert(password: string, title: string, description: string, date: string): Promise<void>;
    addJob(password: string, title: string, department: string, category: Type, vacancies: bigint, lastDate: string, qualification: string, applyLink: string, postedDate: string): Promise<void>;
    addSampleData(password: string): Promise<void>;
    deleteAlert(password: string, id: bigint): Promise<void>;
    deleteJob(password: string, id: bigint): Promise<void>;
    getAllActiveAlerts(): Promise<Array<Alert>>;
    getAllActiveJobs(): Promise<Array<Job>>;
    getJobById(id: bigint): Promise<Job>;
    getJobsByCategory(category: Type): Promise<Array<Job>>;
    updateAlert(password: string, id: bigint, title: string, description: string, date: string, isActive: boolean): Promise<void>;
    updateJob(password: string, id: bigint, title: string, department: string, category: Type, vacancies: bigint, lastDate: string, qualification: string, applyLink: string, isActive: boolean, postedDate: string): Promise<void>;
}
import type { Job as _Job, Type as _Type } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAlert(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAlert(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAlert(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addJob(arg0: string, arg1: string, arg2: string, arg3: Type, arg4: bigint, arg5: string, arg6: string, arg7: string, arg8: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(arg0, arg1, arg2, to_candid_Type_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(arg0, arg1, arg2, to_candid_Type_n1(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async addSampleData(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSampleData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSampleData(arg0);
            return result;
        }
    }
    async deleteAlert(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAlert(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAlert(arg0, arg1);
            return result;
        }
    }
    async deleteJob(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0, arg1);
            return result;
        }
    }
    async getAllActiveAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveAlerts();
            return result;
        }
    }
    async getAllActiveJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveJobs();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveJobs();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobById(arg0: bigint): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobById(arg0);
                return from_candid_Job_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobById(arg0);
            return from_candid_Job_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByCategory(arg0: Type): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByCategory(to_candid_Type_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByCategory(to_candid_Type_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAlert(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAlert(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAlert(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateJob(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: Type, arg5: bigint, arg6: string, arg7: string, arg8: string, arg9: boolean, arg10: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, to_candid_Type_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(arg0, arg1, arg2, arg3, to_candid_Type_n1(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
}
function from_candid_Job_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    applyLink: string;
    postedDate: string;
    vacancies: bigint;
    isActive: boolean;
    category: _Type;
    department: string;
    lastDate: string;
    qualification: string;
}): {
    id: bigint;
    title: string;
    applyLink: string;
    postedDate: string;
    vacancies: bigint;
    isActive: boolean;
    category: Type;
    department: string;
    lastDate: string;
    qualification: string;
} {
    return {
        id: value.id,
        title: value.title,
        applyLink: value.applyLink,
        postedDate: value.postedDate,
        vacancies: value.vacancies,
        isActive: value.isActive,
        category: from_candid_Type_n6(_uploadFile, _downloadFile, value.category),
        department: value.department,
        lastDate: value.lastDate,
        qualification: value.qualification
    };
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    csc: null;
} | {
    railway: null;
} | {
    stateGovt: null;
} | {
    banking: null;
} | {
    defence: null;
} | {
    centralGovt: null;
}): Type {
    return "csc" in value ? Type.csc : "railway" in value ? Type.railway : "stateGovt" in value ? Type.stateGovt : "banking" in value ? Type.banking : "defence" in value ? Type.defence : "centralGovt" in value ? Type.centralGovt : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Type_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    csc: null;
} | {
    railway: null;
} | {
    stateGovt: null;
} | {
    banking: null;
} | {
    defence: null;
} | {
    centralGovt: null;
} {
    return value == Type.csc ? {
        csc: null
    } : value == Type.railway ? {
        railway: null
    } : value == Type.stateGovt ? {
        stateGovt: null
    } : value == Type.banking ? {
        banking: null
    } : value == Type.defence ? {
        defence: null
    } : value == Type.centralGovt ? {
        centralGovt: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
